# -*- coding: utf-8 -*-
"""TESTE.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-v8MjGzTkEVMcLqEy5dw_aA-isZwpzft

## Este teste será divido em duas  partes. Serão avaliadas noções de negócios, noções de SQL e noções de construção de dashboards.

Na primeira parte você responderá perguntas sobre noções de negócio. Em seguida responderá perguntas relacionadas ao desenvolvimento de consultas SQL. E por fim você deverá construir um dashboard que responda as perguntas de negócio e traga novos insigths sobre os dados apresentados.

**Você pode entregar até onde conseguir fazer o teste, até mesmo propor outras soluções que achar necessário. Não fique preso apenas ao que é solicitado!** 😀

## Noções de Negócios

Aqui vamos avaliar questões do dia a dia, sobre como lidar com a equipe e o cliente.

1. Você é designado para um cliente com o objetivo de desenvolver um dashboard para a equipe Comercial. Você nunca trabalhou com este cliente e não tem contexto dos dados. Quais seriam seus passos para o desenvolvimento do trabalho?

Para começar eu faria uma reunião de kickoff com nosso setor comercial (que vendeu o projeto) para entender a ideia inicial.  

Depois faria a reunião de briefing com o cliente, pois é importante entender quais são os objetivos que o conduziram a fazer pesquisa, o que ele espera entender, quais são seu objetivos, dentre outros.    
Após essa reunião, eu estaria munida com as seguintes informações:

1-Teria uma ideia de como funciona a empresa (seu ramo de negócio, quem são seus clientes e etc).   
2-Poderia baixar ou solicitar a paleta de cores da empresa, logos e maneiras de utilização visual da marca
3-Objetivos da pesquisa, então conseguiria já criar os insights, a partir dos dados  

Diante disso eu daria o start no desenvolvimento do Dash. Primeiro organizaria os dados, depois pensaria em quais gráficos e ideias são mais interessantes para cada uma das páginas do BI, e iria fazendo no "Dasktop" e testando na versão "Serviço".   

Quando estivesse pronto e revisado, mandaria o link para a revisão do meu superior, para críticas, correções, alterações, opiniões, enfim o que fosse cabível. Feitas todas as etapas do desenvolmento desse trabalho, o produto estaria pronto para ser entregue através de uma apresentação para o cliente.

2. Como você traçaria um processo de validação de dados e consistencia das regras de negócio implementadas?

A validação dos dados seria feita através da verificação das lógicas do  questionários. Identificaria todas as questões não obrigatórias com lógicas. 

Por exemplo, "Qual o número do seu sapato" essa pergunta somente poderia ser respondida por mulheres que calçassem <=38, então inseriria exatamente essa regra na questão. Se houvesse uma célula respondida referente a um homem, então teria uma incosistênica e a resposta deveria ser excluída, pois homens não deveriam ter respondido. Se quem respondeu fosse uma mulher que calça 40, então esse número tambémm deveria ser apagado. 

Esse é um tipo de consistência que deveria ser feito na base de dados para validá-la. Já em relação as regras de negócio a serem implementadas pela empresa, tendo validado os dados, os valores indicarão quais são as melhores estratégias a serem implementadas. 

Por exemplo, se fosse uma pesquisa sobre o consumo de maquiagem de uma empresa X, cujo universo fossem suas clientes e os dados demonstrassem que:
(1) A maioria das mulheres esta satisfeita com a qualidade dos protudos, (2)tem a pretensão de continuar comprando, isto é, irá se manter fiel e (3) dizem que se houver a criação de uma nova linha, continuariam comprando ainda que seja um pouco mais cara, pois acreditam que os produtos serão mais modernos. 
Veja, estamos falando sempre da maioria (mais do que 50% das/os entrevidas/os), sendo assim, é claramente recomendado que a empresa mantenha sua produção habital, suas regras de negócio, mas também pode lançar essa nova linha mais custosa, pois haverá boa receptividade por parte de suas clientes.

# TESTE PRÁTICO DE LINGUAGEM DE CONSULTA ESTRUTURADA (SQL)
Para a realização das atividades, você deverá executar as instruções abaixo para importar as bibliotecas e funções necessárias para criar a base de dados.

Ao final, esperamos que você desenvolva os códigos selecionados e entregue o notebook com as consultas SQL desenvolvidas e o arquivo .db criado.

O teste importará três arquivos cruciais para o desenvolvimento dessa atividade. Todos estão no Githun (não mude as URL's).

*   usuarios.csv
*   produtos.csv
*   vendas.csv

## O teste foi desenvolvido para ser executado com o SQLite3 e no Google Colab (Ubuntu 18.04). Você deverá utilizar consultas no padrão ANSI. Os comandos necessários podem ser encontrados em:

https://www.sqlite.org/docs.html

https://www.tutorialspoint.com/sqlite/index.htm

# AVISO!



1.   Execute o código abaixo para atualizar a biblioteca do SQLite3 utilizada para essa atividade
2.   **Ignore as mensagens de erro sobre perda de conectividade na instrução abaixo (o kernel será reiniciado para atualização do SQLite3)**
"""

# Commented out IPython magic to ensure Python compatibility.
import os

# BAIXAR A ÚLTIMA RELEASE DO COLAB, DESCOMPACTAR E INSTALAR NO DIRETÓRIO DO 
# PYTHON 3.7 (VERSÃO USADA PELO COLAB NESSE NOTEBOOK)
!curl https://www.sqlite.org/src/tarball/sqlite.tar.gz?r=release | tar xz
# %cd sqlite/
!./configure
!make sqlite3.c
# %cd /content/sqlite/
!npx degit coleifer/pysqlite3 -f
!cp sqlite/sqlite3.[ch] .
!python setup.py build_static build
!cp build/lib.linux-x86_64-3.7/pysqlite3/_sqlite3.cpython-37m-x86_64-linux-gnu.so \
     /usr/lib/python3.7/lib-dynload/

# REINICIANDO O KERNEL DO COLAB PARA IMPORTAR A BIBLIOTECA ATUALIZADA
os.kill(os.getpid(), 9)

"""# INSTRUÇÕES PARA REALIZAR AS CONSULTAS
### PARA CONSULTAR DADOS, SIGA OS PASSOS ABAIXO:

#### Abrir conexão:
    conexao_sql = sqlite3.connect(banco)
#### Abrir cursor para executar consulta no banco:
    cursor = conexao_sql.cursor()
#### Criar uma consulta:
    consulta = '''
        Coloque aqui a sua instrução SQL;
    '''
    cursor.execute(consulta)
#### Para visualizar o resultado da sua consulta:
    for linha in cursor:
      print(linha)
#### Para fechar a conexão:
    conexao_sql.close()

### LEMBRE-SE DE QUE PYTHON É SENSÍVEL A IDENTAÇÃO DE CÓDIGO!

# IMPORTANDO BIBLIOTECAS NECESSÁRIAS PARA EXECUTAR OS CÓDIGOS EM SQL
"""

import sqlite3
import csv
import requests
from pathlib import Path
from urllib.parse import urlparse

"""# DEFINIÇÃO DE VARIÁVEIS FIXAS PARA O PROJETO"""

banco = "teste_sql.db"

"""# FUNÇÃO PARA INSERIR REGISTROS NO BANCO DE DADOS"""

# Recebe como parâmetro
# 1. Nome do banco de dados
# 2. Nome da tabela que receberá os dados
# 3. Lista das colunas da tabela
# 4. Dados que serão inseridos

def inserir_registros(banco, tabela, lista_colunas, arquivo):
  conexao_sql = sqlite3.connect(banco)
  cursor = conexao_sql.cursor()
  dados = open(arquivo)
  conteudo_dados = csv.reader(dados)
  num_colunas = 1 if lista_colunas.count(',') == 1 else lista_colunas.count(',')
  string_insert = 'INSERT INTO ' + tabela + ' (' + lista_colunas + ') VALUES (?' + ('' if num_colunas == 1 else ', ?' * (num_colunas)) + ')'
  cursor.executemany(string_insert, conteudo_dados)
  conexao_sql.commit()
  conexao_sql.close()

"""# FUNÇÃO PARA BAIXAR A BASE DE DADOS UTILIZADA PARA DESENVOLVIMENTO DAS ATIVIDADES"""

# Recebe como parâmetro:
# 1. Nome do arquivo com a extensão (Ex: base.csv)
# 2. URL do site onde o dado está localizado (Ex: 'https://drive.google.com/user_teste/folder_dataset/file.csv'):

def baixar_dados(nome_arquivo, url):
  requisicao = requests.get(url)
  conteudo = requisicao.content
  arquivo_csv = open(nome_arquivo, 'wb')
  arquivo_csv.write(conteudo)
  arquivo_csv.close()

"""# CRIAÇÃO DE CONEXÃO COM O BANCO SQLITE3 PARA DESENVOLVIMENTO DA ATIVIDADE"""

# Abre conexão com o banco. Se o arquivo não existir, cria a base.
conexao_sql = sqlite3.connect(banco)
conexao_sql.close()

"""# CRIAÇÃO DAS TABELAS PARA REALIZAÇÃO DAS ATIVIDADES

### TABELA DE USUÁRIOS
"""

url = 'https://raw.githubusercontent.com/A3Data/testes_praticos/main/sql/base_dados/usuarios.csv'
nome_arquivo = Path(urlparse(url).path).name
baixar_dados(nome_arquivo, url)

conexao_sql = sqlite3.connect(banco)
# CRIAR A TABELA
conexao_sql.execute('''
CREATE TABLE IF NOT EXISTS usuarios
(
  cod_usuario INTEGER NOT NULL,
  data_cadastro DATE NOT NULL,
  faixa_etaria TEXT,
  cidade TEXT NOT NULL,
  estado TEXT NOT NULL);'''
)
conexao_sql.commit()

# INSERIR OS REGISTROS NO BANCO DE DADOS
lista_campos = 'cod_usuario, data_cadastro, faixa_etaria, cidade, estado'
inserir_registros(banco, 'usuarios', lista_campos, nome_arquivo)

"""### TABELA DE PRODUTOS"""

url = 'https://raw.githubusercontent.com/A3Data/testes_praticos/main/sql/base_dados/produtos.csv'
nome_arquivo = Path(urlparse(url).path).name
baixar_dados(nome_arquivo, url)

conexao_sql = sqlite3.connect(banco)
arquivo_produtos = 'produtos.csv'
# CRIAR A TABELA
conexao_sql.execute('''
CREATE TABLE IF NOT EXISTS produtos
(
  cod_produto INTEGER NOT NULL,
  nome_produto TEXT NOT NULL,
  categoria_produto TEXT,
  valor_produto FLOAT);'''
)
conexao_sql.commit()

# INSERIR OS REGISTROS NO BANCO DE DADOS
lista_campos = 'cod_produto, nome_produto, categoria_produto, valor_produto'
inserir_registros(banco, 'produtos', lista_campos, arquivo_produtos)

"""### TABELA DE VENDAS"""

url = 'https://raw.githubusercontent.com/A3Data/testes_praticos/main/sql/base_dados/vendas.csv'
nome_arquivo = Path(urlparse(url).path).name
baixar_dados(nome_arquivo, url)

conexao_sql = sqlite3.connect(banco)
arquivo_vendas = 'vendas.csv'
# CRIAR A TABELA
conexao_sql.execute('''
CREATE TABLE IF NOT EXISTS vendas
(
  cod_usuario INTEGER NOT NULL,
  cod_produto INTEGER NOT NULL,
  data_compra DATE NOT NULL,
  quantidade INT NOT NULL,
  valor FLOAT NOT NULL);'''
)
conexao_sql.commit()

# INSERIR OS REGISTROS NO BANCO DE DADOS
lista_campos = 'cod_usuario, cod_produto, data_compra, quantidade, valor'
inserir_registros(banco, 'vendas', lista_campos, arquivo_vendas)

"""## Pergunta 1:


 Escreva um comando em SQL que retorne a quantidade de venda do estado de Minas Gerais por ano e mês
"""

from sqlite3.dbapi2 import SQLITE_SELECT

cursor = conexao_sql.cursor()

consulta = '''
SELECT strftime('%Y-%m',data_compra) as data,
  sum(quantidade) 
  FROM vendas 
    WHERE cod_usuario IN (SELECT cod_usuario FROM usuarios WHERE estado like "Minas Gerais")
GROUP BY data
'''

cursor.execute(consulta)
for linha in cursor:
  print(linha)

"""## Pergunta 2:

Escreva um comando em SQL que retorne quais são os 3 produtos mais comprados por estado, a quantidade de itens comprados, o valor total pago e a média de preço paga
"""

from sqlite3.dbapi2 import SQLITE_SELECT

cursor = conexao_sql.cursor()

consulta = '''
SELECT produtos.nome_produto, sum(vendas.quantidade), sum(vendas.valor), avg(vendas.valor), usuarios.estado
FROM vendas, produtos, usuarios
WHERE vendas.cod_usuario = usuarios.cod_usuario 
GROUP BY usuarios.estado
'''
cursor.execute(consulta)
for linha in cursor:
  print(linha)

"""## Pergunta 3

Escreva um comando em SQL que retorne o produto, a quantidade de itens vendidos e a receita do produto que tem mais itens vendidos por ano e mês
"""

from sqlite3.dbapi2 import SQLITE_SELECT

cursor = conexao_sql.cursor()

consulta = '''
SELECT produtos.nome_produto, vendas.quantidade, vendas.quantidade * valor_produto, 
strftime('%Y',vendas.data_compra) as data1, strftime('%m',vendas.data_compra) as data2
  FROM vendas, produtos
  WHERE vendas.cod_produto = produtos.cod_produto
  GROUP BY data1, data2
  HAVING vendas.quantidade = max(vendas.quantidade)



'''
cursor.execute(consulta) 
for linha in cursor:
  print(linha)

"""# **Construção de dashboard** 


**Seu desafio é desenvolver uma análise dos dados de vendas disponibilizados pela Data Coporation, com o intuito de gerar insights para os gestores responsáveis.**

O dashboard deverá conter apenas uma página e ser desenvolvido em Power BI.

Segue algumas perguntas feitas pelos gestores que devem ser abordadas:

1. O gerente geral da Data Corporation decidiu abrir operação de lojas fisicas em quatro cidades. Quais cidades você indicaria baseado no histórico de compras?

2. Para abrir a operação de lojas fisicas o gerante também precisa decidir qual categoria ele deve investir, pensando em retorno financeiro. Além disso ele gostaria de indicações de produtos que possam alanvancar as vendas nos primeiros 6 meses. A proposta é que a abertura aconteça nos meses de janeiro e fevereiro. Qual seria sua indicação?


**Não fique preso nas perguntas acima, novos insights são sempre bem vindos!**


LINK PARA ACESSAR O POWER BI DA NAIARA: https://app.powerbi.com/view?r=eyJrIjoiNDc1ZjlkMGYtZWM3OC00MzQ4LTk1MmQtMzAxMDFkNDMwMDNlIiwidCI6IjM3MWYxZjdjLTA4OTQtNDFkMi04M2M5LTNlZWNkZmU2ODc1OCJ9&pageName=ReportSection


<iframe title="PowerBi NaiAlcantara" width="600" height="373.5" src="https://app.powerbi.com/view?r=eyJrIjoiNDc1ZjlkMGYtZWM3OC00MzQ4LTk1MmQtMzAxMDFkNDMwMDNlIiwidCI6IjM3MWYxZjdjLTA4OTQtNDFkMi04M2M5LTNlZWNkZmU2ODc1OCJ9&pageName=ReportSection" frameborder="0" allowFullScreen="true"></iframe>


"""